apiVersion: v1
kind: Pod
metadata:
  name: priviledged-spikey-pod
spec:
  containers:
    - name: spikey-website-pod
      image: gcr.io/srianjaneyam/spikey-website:v1
      securityContext:
        privileged: true