apiVersion: v1
kind: Pod
metadata:
  name: priviledged-bk-pod
spec:
  containers:
    - name: bk-website-pod
      image: gcr.io/srianjaneyam/bk-website:v1
      securityContext:
        privileged: true