apiVersion: apps/v1
kind: Deployment
metadata:
  name: bk-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bk-website
  template:
    metadata:
      labels:
        app: bk-website
    spec:
      containers:
      - name: bk-website
        image: gcr.io/srianjaneyam/bk-website:v1
        ports:
        - containerPort: 8080
