apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bk-website
spec:
  serviceName: bk-website
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: bk-website
  template:
    metadata:
      labels:
        app: bk-website
    spec:
      containers:
      - name: bk-website
        image:  gcr.io/srianjaneyam/bk-website:v1
        ports:
        - containerPort: 80
          name: bk-website
        volumeMounts:
        - name: bk-website-pv
          mountPath: /bk-website-pv
  volumeClaimTemplates:
  - metadata:
      name: bk-website-pv
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi