apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: weekly-ratings-cronjob
spec:
  schedule: "18 */1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: customer-ratings
            image: gcr.io/srianjaneyam/customer-ratings:v1
          restartPolicy: OnFailure